# Generated by Django 4.0.2 on 2022-03-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map', to='projectapp.project'),
        ),
    ]
